"""
topic_registry.py — Central registry of all 23 hypothesis test topics.

Contains metadata for each topic including:
- Display name
- Test statistic formula (Unicode)
- Degrees of freedom formula
- Effect size measure and formula
- Confidence interval formula
- Cross-reference map (related tests)
- Distribution type (for plotting)

Claude Code should import this when building any topic to ensure
consistency across all generated files.

Usage:
    from scripts.topic_registry import TOPICS, get_topic

    t = get_topic("one_sample_z_test")
    print(t["display_name"])       # "One-Sample Z-Test"
    print(t["test_stat_formula"])  # "z = (x̄ − μ₀) / (σ / √n)"
    print(t["see_also"])           # [("one_sample_t_test", "when σ ..."), ...]
"""

TOPICS = {
    "one_sample_z_test": {
        "display_name": "One-Sample Z-Test",
        "category": "One-Sample Tests",
        "description": "Tests whether a population mean equals a hypothesized value when the population standard deviation σ is known.",
        "test_stat_formula": "z = (x̄ − μ₀) / (σ / √n)",
        "test_stat_symbols": {
            "x̄": "sample mean",
            "μ₀": "hypothesized population mean",
            "σ": "known population standard deviation",
            "n": "sample size",
        },
        "df_formula": None,
        "ci_formula": "x̄ ± z_(α/2) · (σ / √n)",
        "effect_size_name": "Cohen's d",
        "effect_size_formula": "d = (x̄ − μ₀) / σ",
        "effect_size_scale": {"small": 0.2, "medium": 0.5, "large": 0.8},
        "distribution": "normal",
        "scipy_function": "scipy.stats.norm (manual calculation)",
        "see_also": [
            ("one_sample_t_test", "Use when σ is unknown"),
            ("shapiro_wilk_test", "To verify the normality assumption"),
        ],
    },
    "one_sample_t_test": {
        "display_name": "One-Sample T-Test",
        "category": "One-Sample Tests",
        "description": "Tests whether a population mean equals a hypothesized value when the population standard deviation σ is unknown.",
        "test_stat_formula": "t = (x̄ − μ₀) / (s / √n)",
        "test_stat_symbols": {
            "x̄": "sample mean",
            "μ₀": "hypothesized population mean",
            "s": "sample standard deviation",
            "n": "sample size",
        },
        "df_formula": "df = n − 1",
        "ci_formula": "x̄ ± t_(α/2, df) · (s / √n)",
        "effect_size_name": "Cohen's d",
        "effect_size_formula": "d = (x̄ − μ₀) / s",
        "effect_size_scale": {"small": 0.2, "medium": 0.5, "large": 0.8},
        "distribution": "t",
        "scipy_function": "scipy.stats.ttest_1samp",
        "see_also": [
            ("one_sample_z_test", "Use when σ is known"),
            ("paired_t_test", "Use when data are matched pairs"),
            ("shapiro_wilk_test", "To verify the normality assumption"),
            ("wilcoxon_signed_rank", "Nonparametric alternative"),
        ],
    },
    "one_sample_proportion_z_test": {
        "display_name": "One-Sample Proportion Z-Test",
        "category": "One-Sample Tests",
        "description": "Tests whether a population proportion equals a hypothesized value.",
        "test_stat_formula": "z = (p̂ − p₀) / √(p₀(1 − p₀) / n)",
        "test_stat_symbols": {
            "p̂": "sample proportion",
            "p₀": "hypothesized population proportion",
            "n": "sample size",
        },
        "df_formula": None,
        "ci_formula": "p̂ ± z_(α/2) · √(p̂(1 − p̂) / n)",
        "effect_size_name": "Cohen's h",
        "effect_size_formula": "h = 2·arcsin(√p̂) − 2·arcsin(√p₀)",
        "effect_size_scale": {"small": 0.2, "medium": 0.5, "large": 0.8},
        "distribution": "normal",
        "scipy_function": "statsmodels.stats.proportion.proportions_ztest",
        "see_also": [
            ("two_proportion_z_test", "Use when comparing two groups"),
            ("chi_square_goodness_of_fit", "Use for multiple categories"),
        ],
    },
    "two_sample_z_test": {
        "display_name": "Two-Sample Z-Test",
        "category": "Two-Sample Tests",
        "description": "Tests whether two population means are equal when both population standard deviations are known.",
        "test_stat_formula": "z = (x̄₁ − x̄₂) / √(σ₁²/n₁ + σ₂²/n₂)",
        "test_stat_symbols": {
            "x̄₁, x̄₂": "sample means",
            "σ₁, σ₂": "known population standard deviations",
            "n₁, n₂": "sample sizes",
        },
        "df_formula": None,
        "ci_formula": "(x̄₁ − x̄₂) ± z_(α/2) · √(σ₁²/n₁ + σ₂²/n₂)",
        "effect_size_name": "Cohen's d",
        "effect_size_formula": "d = (x̄₁ − x̄₂) / √((σ₁² + σ₂²) / 2)",
        "effect_size_scale": {"small": 0.2, "medium": 0.5, "large": 0.8},
        "distribution": "normal",
        "scipy_function": "scipy.stats.norm (manual calculation)",
        "see_also": [
            ("two_sample_t_test_equal_var", "Use when σ is unknown"),
            ("welchs_t_test", "Use when σ is unknown and variances are unequal"),
        ],
    },
    "two_sample_t_test_equal_var": {
        "display_name": "Two-Sample T-Test (Equal Variances)",
        "category": "Two-Sample Tests",
        "description": "Tests whether two population means are equal, assuming equal population variances.",
        "test_stat_formula": "t = (x̄₁ − x̄₂) / (s_p · √(1/n₁ + 1/n₂))\nwhere s_p = √(((n₁−1)s₁² + (n₂−1)s₂²) / (n₁+n₂−2))",
        "test_stat_symbols": {
            "x̄₁, x̄₂": "sample means",
            "s₁, s₂": "sample standard deviations",
            "s_p": "pooled standard deviation",
            "n₁, n₂": "sample sizes",
        },
        "df_formula": "df = n₁ + n₂ − 2",
        "ci_formula": "(x̄₁ − x̄₂) ± t_(α/2, df) · s_p · √(1/n₁ + 1/n₂)",
        "effect_size_name": "Cohen's d",
        "effect_size_formula": "d = (x̄₁ − x̄₂) / s_p",
        "effect_size_scale": {"small": 0.2, "medium": 0.5, "large": 0.8},
        "distribution": "t",
        "scipy_function": "scipy.stats.ttest_ind(equal_var=True)",
        "see_also": [
            ("welchs_t_test", "Use when equal variance assumption fails"),
            ("f_test_two_variances", "Test the equal variance assumption first"),
            ("mann_whitney_u", "Nonparametric alternative"),
            ("shapiro_wilk_test", "To verify normality"),
        ],
    },
    "welchs_t_test": {
        "display_name": "Welch's T-Test",
        "category": "Two-Sample Tests",
        "description": "Tests whether two population means are equal without assuming equal variances.",
        "test_stat_formula": "t = (x̄₁ − x̄₂) / √(s₁²/n₁ + s₂²/n₂)",
        "test_stat_symbols": {
            "x̄₁, x̄₂": "sample means",
            "s₁, s₂": "sample standard deviations",
            "n₁, n₂": "sample sizes",
        },
        "df_formula": "df = (s₁²/n₁ + s₂²/n₂)² / ((s₁²/n₁)²/(n₁−1) + (s₂²/n₂)²/(n₂−1))  (Welch-Satterthwaite)",
        "ci_formula": "(x̄₁ − x̄₂) ± t_(α/2, df) · √(s₁²/n₁ + s₂²/n₂)",
        "effect_size_name": "Cohen's d",
        "effect_size_formula": "d = (x̄₁ − x̄₂) / √((s₁² + s₂²) / 2)",
        "effect_size_scale": {"small": 0.2, "medium": 0.5, "large": 0.8},
        "distribution": "t",
        "scipy_function": "scipy.stats.ttest_ind(equal_var=False)",
        "see_also": [
            ("two_sample_t_test_equal_var", "Use when variances are equal"),
            ("mann_whitney_u", "Nonparametric alternative"),
        ],
    },
    "paired_t_test": {
        "display_name": "Paired T-Test",
        "category": "Two-Sample Tests",
        "description": "Tests whether the mean difference between paired observations is zero.",
        "test_stat_formula": "t = d̄ / (s_d / √n)",
        "test_stat_symbols": {
            "d̄": "mean of the differences (d = x₁ − x₂ for each pair)",
            "s_d": "standard deviation of the differences",
            "n": "number of pairs",
        },
        "df_formula": "df = n − 1",
        "ci_formula": "d̄ ± t_(α/2, df) · (s_d / √n)",
        "effect_size_name": "Cohen's d",
        "effect_size_formula": "d = d̄ / s_d",
        "effect_size_scale": {"small": 0.2, "medium": 0.5, "large": 0.8},
        "distribution": "t",
        "scipy_function": "scipy.stats.ttest_rel",
        "see_also": [
            ("one_sample_t_test", "Equivalent test applied to the differences"),
            ("wilcoxon_signed_rank", "Nonparametric alternative"),
            ("sign_test", "Nonparametric alternative for ordinal data"),
        ],
    },
    "two_proportion_z_test": {
        "display_name": "Two-Proportion Z-Test",
        "category": "Two-Sample Tests",
        "description": "Tests whether two population proportions are equal.",
        "test_stat_formula": "z = (p̂₁ − p̂₂) / √(p̂(1−p̂)(1/n₁ + 1/n₂))\nwhere p̂ = (x₁ + x₂) / (n₁ + n₂)  (pooled proportion)",
        "test_stat_symbols": {
            "p̂₁, p̂₂": "sample proportions",
            "p̂": "pooled sample proportion",
            "x₁, x₂": "number of successes in each sample",
            "n₁, n₂": "sample sizes",
        },
        "df_formula": None,
        "ci_formula": "(p̂₁ − p̂₂) ± z_(α/2) · √(p̂₁(1−p̂₁)/n₁ + p̂₂(1−p̂₂)/n₂)",
        "effect_size_name": "Cohen's h",
        "effect_size_formula": "h = 2·arcsin(√p̂₁) − 2·arcsin(√p̂₂)",
        "effect_size_scale": {"small": 0.2, "medium": 0.5, "large": 0.8},
        "distribution": "normal",
        "scipy_function": "statsmodels.stats.proportion.proportions_ztest",
        "see_also": [
            ("one_sample_proportion_z_test", "Use for a single proportion"),
            ("chi_square_independence", "Use for more than 2 groups"),
            ("fishers_exact_test", "Use for small samples"),
        ],
    },
    "chi_square_goodness_of_fit": {
        "display_name": "Chi-Square Goodness-of-Fit Test",
        "category": "Chi-Square Tests",
        "description": "Tests whether observed frequencies match an expected distribution for a single categorical variable.",
        "test_stat_formula": "χ² = Σ (Oᵢ − Eᵢ)² / Eᵢ",
        "test_stat_symbols": {
            "Oᵢ": "observed frequency for category i",
            "Eᵢ": "expected frequency for category i",
            "k": "number of categories",
        },
        "df_formula": "df = k − 1",
        "ci_formula": "Not applicable (no single parameter being estimated).",
        "effect_size_name": "Cohen's w",
        "effect_size_formula": "w = √(Σ (p_obs − p_exp)² / p_exp)",
        "effect_size_scale": {"small": 0.1, "medium": 0.3, "large": 0.5},
        "distribution": "chi2",
        "scipy_function": "scipy.stats.chisquare",
        "see_also": [
            ("one_sample_proportion_z_test", "Use for a single proportion with 2 categories"),
            ("shapiro_wilk_test", "Use for testing normality specifically"),
        ],
    },
    "chi_square_independence": {
        "display_name": "Chi-Square Test of Independence",
        "category": "Chi-Square Tests",
        "description": "Tests whether two categorical variables are independent using a contingency table.",
        "test_stat_formula": "χ² = Σ Σ (Oᵢⱼ − Eᵢⱼ)² / Eᵢⱼ\nwhere Eᵢⱼ = (Row i Total × Col j Total) / Grand Total",
        "test_stat_symbols": {
            "Oᵢⱼ": "observed frequency in cell (i, j)",
            "Eᵢⱼ": "expected frequency in cell (i, j)",
            "r": "number of rows",
            "c": "number of columns",
        },
        "df_formula": "df = (r − 1)(c − 1)",
        "ci_formula": "Not applicable (tests association, not a single parameter).",
        "effect_size_name": "Cramér's V",
        "effect_size_formula": "V = √(χ² / (n · min(r−1, c−1)))",
        "effect_size_scale": {"small": 0.1, "medium": 0.3, "large": 0.5},
        "distribution": "chi2",
        "scipy_function": "scipy.stats.chi2_contingency",
        "see_also": [
            ("fishers_exact_test", "Use when expected counts < 5"),
            ("two_proportion_z_test", "Equivalent for a 2×2 table"),
        ],
    },
    "fishers_exact_test": {
        "display_name": "Fisher's Exact Test",
        "category": "Chi-Square Tests",
        "description": "Tests independence in a 2×2 contingency table using exact probabilities, suitable when expected counts are small (< 5).",
        "test_stat_formula": "p = (a+b)!(c+d)!(a+c)!(b+d)! / (n! · a! · b! · c! · d!)\n(hypergeometric probability for each possible table)",
        "test_stat_symbols": {
            "a, b, c, d": "cell counts in the 2×2 table",
            "n": "grand total",
        },
        "df_formula": "Not applicable (exact test, no asymptotic distribution)",
        "ci_formula": "CI for odds ratio: computed via exact method",
        "effect_size_name": "Odds Ratio",
        "effect_size_formula": "OR = (a · d) / (b · c)",
        "effect_size_scale": {"small": 1.5, "medium": 2.5, "large": 4.3},
        "distribution": "hypergeometric",
        "scipy_function": "scipy.stats.fisher_exact",
        "see_also": [
            ("chi_square_independence", "Use when expected counts are all ≥ 5"),
            ("two_proportion_z_test", "Large-sample alternative"),
        ],
    },
    "shapiro_wilk_test": {
        "display_name": "Shapiro-Wilk Test for Normality",
        "category": "Normality Testing",
        "description": "Tests whether a sample comes from a normally distributed population.",
        "test_stat_formula": "W = (Σ aᵢ x_(i))² / Σ (xᵢ − x̄)²",
        "test_stat_symbols": {
            "W": "Shapiro-Wilk test statistic (0 to 1; closer to 1 = more normal)",
            "aᵢ": "tabulated constants based on sample size",
            "x_(i)": "i-th order statistic (sorted data values)",
            "x̄": "sample mean",
        },
        "df_formula": "Not applicable (use tables or p-value directly)",
        "ci_formula": "Not applicable (this test checks an assumption, not a parameter).",
        "effect_size_name": "W statistic itself",
        "effect_size_formula": "W (closer to 1 indicates stronger normality)",
        "effect_size_scale": {"normal": "W > 0.95", "borderline": "0.90 < W < 0.95", "non-normal": "W < 0.90"},
        "distribution": "shapiro_wilk_tables",
        "scipy_function": "scipy.stats.shapiro",
        "see_also": [
            ("one_sample_t_test", "Requires normality assumption"),
            ("paired_t_test", "Requires normality of differences"),
            ("one_way_anova", "Requires normality within groups"),
        ],
    },
    "one_way_anova": {
        "display_name": "One-Way ANOVA",
        "category": "ANOVA",
        "description": "Tests whether the means of three or more independent groups are all equal.",
        "test_stat_formula": "F = MS_between / MS_within\nwhere MS = SS / df",
        "test_stat_symbols": {
            "SS_between": "sum of squares between groups",
            "SS_within": "sum of squares within groups",
            "MS_between": "mean square between = SS_between / (k − 1)",
            "MS_within": "mean square within = SS_within / (N − k)",
            "k": "number of groups",
            "N": "total sample size",
        },
        "df_formula": "df₁ = k − 1 (numerator),  df₂ = N − k (denominator)",
        "ci_formula": "Individual group CIs: x̄ᵢ ± t_(α/2, N−k) · √(MS_within / nᵢ)",
        "effect_size_name": "Eta-squared (η²)",
        "effect_size_formula": "η² = SS_between / SS_total",
        "effect_size_scale": {"small": 0.01, "medium": 0.06, "large": 0.14},
        "distribution": "F",
        "scipy_function": "scipy.stats.f_oneway",
        "see_also": [
            ("kruskal_wallis", "Nonparametric alternative"),
            ("two_way_anova", "Use with two factors"),
            ("two_sample_t_test_equal_var", "Use with only 2 groups"),
            ("f_test_two_variances", "To check homogeneity of variance"),
        ],
    },
    "two_way_anova": {
        "display_name": "Two-Way ANOVA",
        "category": "ANOVA",
        "description": "Tests the effects of two factors (and their interaction) on a continuous outcome.",
        "test_stat_formula": "F_A = MS_A / MS_error\nF_B = MS_B / MS_error\nF_AB = MS_AB / MS_error",
        "test_stat_symbols": {
            "MS_A": "mean square for factor A",
            "MS_B": "mean square for factor B",
            "MS_AB": "mean square for interaction",
            "MS_error": "mean square error (within-groups)",
        },
        "df_formula": "df_A = a−1,  df_B = b−1,  df_AB = (a−1)(b−1),  df_error = N − ab",
        "ci_formula": "Cell mean CIs: x̄ᵢⱼ ± t_(α/2, df_error) · √(MS_error / nᵢⱼ)",
        "effect_size_name": "Eta-squared (η²) for each factor",
        "effect_size_formula": "η²_A = SS_A / SS_total,  η²_B = SS_B / SS_total,  η²_AB = SS_AB / SS_total",
        "effect_size_scale": {"small": 0.01, "medium": 0.06, "large": 0.14},
        "distribution": "F",
        "scipy_function": "statsmodels.stats.anova.anova_lm (Type II)",
        "see_also": [
            ("one_way_anova", "Use with a single factor"),
            ("kruskal_wallis", "Nonparametric alternative (single factor only)"),
        ],
    },
    "sign_test": {
        "display_name": "Sign Test",
        "category": "Nonparametric Tests",
        "description": "Tests whether the median of paired differences is zero. Simplest nonparametric test for paired data.",
        "test_stat_formula": "S = number of positive differences\nUnder H₀: S ~ Binomial(n, 0.5)",
        "test_stat_symbols": {
            "S": "count of positive differences",
            "n": "number of non-zero differences (ties excluded)",
        },
        "df_formula": "Not applicable (binomial distribution used directly)",
        "ci_formula": "CI for median: based on order statistics",
        "effect_size_name": "r (effect size)",
        "effect_size_formula": "r = (S − n/2) / (n/2)",
        "effect_size_scale": {"small": 0.1, "medium": 0.3, "large": 0.5},
        "distribution": "binomial",
        "scipy_function": "scipy.stats.binom_test or scipy.stats.binomtest",
        "see_also": [
            ("wilcoxon_signed_rank", "More powerful nonparametric paired test"),
            ("paired_t_test", "Parametric alternative"),
        ],
    },
    "wilcoxon_signed_rank": {
        "display_name": "Wilcoxon Signed-Rank Test",
        "category": "Nonparametric Tests",
        "description": "Tests whether the median of paired differences is zero, using ranks. More powerful than the sign test.",
        "test_stat_formula": "W = min(W⁺, W⁻)\nwhere W⁺ = sum of ranks of positive differences\n      W⁻ = sum of ranks of negative differences",
        "test_stat_symbols": {
            "W⁺": "sum of ranks of positive differences",
            "W⁻": "sum of ranks of negative differences",
            "n": "number of non-zero differences",
        },
        "df_formula": "Not applicable (use Wilcoxon tables or normal approximation for large n)",
        "ci_formula": "CI for median difference: Walsh averages method",
        "effect_size_name": "r (rank-biserial correlation)",
        "effect_size_formula": "r = Z / √n",
        "effect_size_scale": {"small": 0.1, "medium": 0.3, "large": 0.5},
        "distribution": "wilcoxon_tables",
        "scipy_function": "scipy.stats.wilcoxon",
        "see_also": [
            ("paired_t_test", "Parametric alternative"),
            ("sign_test", "Less powerful alternative for ordinal data"),
            ("mann_whitney_u", "Independent samples version"),
        ],
    },
    "mann_whitney_u": {
        "display_name": "Mann-Whitney U Test",
        "category": "Nonparametric Tests",
        "description": "Tests whether two independent samples come from the same distribution (nonparametric alternative to the two-sample t-test).",
        "test_stat_formula": "U = min(U₁, U₂)\nwhere U₁ = n₁n₂ + n₁(n₁+1)/2 − R₁\n      U₂ = n₁n₂ − U₁",
        "test_stat_symbols": {
            "U₁, U₂": "Mann-Whitney U statistics for each group",
            "R₁": "sum of ranks for group 1 (in the combined ranking)",
            "n₁, n₂": "sample sizes",
        },
        "df_formula": "Not applicable (use U tables or normal approximation)",
        "ci_formula": "CI for median difference: Hodges-Lehmann estimator method",
        "effect_size_name": "r (rank-biserial correlation)",
        "effect_size_formula": "r = 1 − (2U) / (n₁ · n₂)",
        "effect_size_scale": {"small": 0.1, "medium": 0.3, "large": 0.5},
        "distribution": "mann_whitney_tables",
        "scipy_function": "scipy.stats.mannwhitneyu",
        "see_also": [
            ("two_sample_t_test_equal_var", "Parametric alternative"),
            ("welchs_t_test", "Parametric alternative"),
            ("wilcoxon_signed_rank", "Paired version"),
            ("kruskal_wallis", "Extension to more than 2 groups"),
        ],
    },
    "kruskal_wallis": {
        "display_name": "Kruskal-Wallis Test",
        "category": "Nonparametric Tests",
        "description": "Tests whether three or more independent groups come from the same distribution (nonparametric alternative to one-way ANOVA).",
        "test_stat_formula": "H = (12 / (N(N+1))) · Σ (Rᵢ² / nᵢ) − 3(N+1)",
        "test_stat_symbols": {
            "H": "Kruskal-Wallis test statistic (approx. χ² distributed)",
            "Rᵢ": "sum of ranks in group i",
            "nᵢ": "sample size of group i",
            "N": "total sample size",
            "k": "number of groups",
        },
        "df_formula": "df = k − 1 (using χ² approximation)",
        "ci_formula": "Not directly applicable (pairwise comparisons for follow-up).",
        "effect_size_name": "Eta-squared (η²_H)",
        "effect_size_formula": "η²_H = (H − k + 1) / (N − k)",
        "effect_size_scale": {"small": 0.01, "medium": 0.06, "large": 0.14},
        "distribution": "chi2",
        "scipy_function": "scipy.stats.kruskal",
        "see_also": [
            ("one_way_anova", "Parametric alternative"),
            ("mann_whitney_u", "Use with only 2 groups"),
        ],
    },
    "correlation_t_test": {
        "display_name": "T-Test for Correlation Coefficient",
        "category": "Regression & Correlation",
        "description": "Tests whether the population correlation coefficient ρ equals zero.",
        "test_stat_formula": "t = r · √(n − 2) / √(1 − r²)",
        "test_stat_symbols": {
            "r": "sample Pearson correlation coefficient",
            "n": "number of data pairs",
            "ρ": "population correlation coefficient (tested: ρ = 0)",
        },
        "df_formula": "df = n − 2",
        "ci_formula": "Fisher z-transform: z_r = 0.5 · ln((1+r)/(1−r)), CI for z_r, then back-transform",
        "effect_size_name": "r² (coefficient of determination)",
        "effect_size_formula": "r² (proportion of variance explained)",
        "effect_size_scale": {"small": 0.01, "medium": 0.09, "large": 0.25},
        "distribution": "t",
        "scipy_function": "scipy.stats.pearsonr",
        "see_also": [
            ("regression_slope_t_test", "Equivalent for simple linear regression"),
            ("regression_f_test", "Overall model significance"),
        ],
    },
    "regression_slope_t_test": {
        "display_name": "T-Test for Regression Slope",
        "category": "Regression & Correlation",
        "description": "Tests whether the slope β₁ in a simple linear regression is zero.",
        "test_stat_formula": "t = b₁ / SE(b₁)\nwhere SE(b₁) = √(MSE / Σ(xᵢ − x̄)²)",
        "test_stat_symbols": {
            "b₁": "estimated slope (least squares)",
            "SE(b₁)": "standard error of the slope",
            "MSE": "mean squared error = SSE / (n − 2)",
        },
        "df_formula": "df = n − 2",
        "ci_formula": "b₁ ± t_(α/2, df) · SE(b₁)",
        "effect_size_name": "R² (coefficient of determination)",
        "effect_size_formula": "R² = SS_regression / SS_total",
        "effect_size_scale": {"small": 0.01, "medium": 0.09, "large": 0.25},
        "distribution": "t",
        "scipy_function": "scipy.stats.linregress",
        "see_also": [
            ("correlation_t_test", "Equivalent test for ρ = 0"),
            ("regression_f_test", "Overall model significance"),
        ],
    },
    "regression_f_test": {
        "display_name": "F-Test for Overall Regression Significance",
        "category": "Regression & Correlation",
        "description": "Tests whether a regression model explains a significant portion of the variance in the response variable.",
        "test_stat_formula": "F = MS_regression / MS_error\nwhere MS_regression = SS_regression / k\n      MS_error = SS_error / (n − k − 1)",
        "test_stat_symbols": {
            "SS_regression": "sum of squares due to regression",
            "SS_error": "residual sum of squares",
            "k": "number of predictors",
            "n": "sample size",
        },
        "df_formula": "df₁ = k (numerator),  df₂ = n − k − 1 (denominator)",
        "ci_formula": "Not applicable to overall F-test (use individual slope CIs).",
        "effect_size_name": "R² and Adjusted R²",
        "effect_size_formula": "R² = SS_regression / SS_total\nAdj R² = 1 − (1−R²)(n−1)/(n−k−1)",
        "effect_size_scale": {"small": 0.01, "medium": 0.09, "large": 0.25},
        "distribution": "F",
        "scipy_function": "scipy.stats.f (manual) or statsmodels OLS",
        "see_also": [
            ("regression_slope_t_test", "Test individual predictors"),
            ("one_way_anova", "Related framework for comparing group means"),
        ],
    },
    "chi_square_variance": {
        "display_name": "Chi-Square Test for a Single Variance",
        "category": "Variance Tests",
        "description": "Tests whether a population variance equals a hypothesized value.",
        "test_stat_formula": "χ² = (n − 1) · s² / σ₀²",
        "test_stat_symbols": {
            "s²": "sample variance",
            "σ₀²": "hypothesized population variance",
            "n": "sample size",
        },
        "df_formula": "df = n − 1",
        "ci_formula": "((n−1)s²/χ²_upper,  (n−1)s²/χ²_lower)  for σ²",
        "effect_size_name": "Variance ratio",
        "effect_size_formula": "s² / σ₀²",
        "effect_size_scale": {"note": "No standard Cohen's scale; interpret in context"},
        "distribution": "chi2",
        "scipy_function": "scipy.stats.chi2 (manual calculation)",
        "see_also": [
            ("f_test_two_variances", "Use to compare two variances"),
        ],
    },
    "f_test_two_variances": {
        "display_name": "F-Test for Equality of Two Variances",
        "category": "Variance Tests",
        "description": "Tests whether two population variances are equal.",
        "test_stat_formula": "F = s₁² / s₂²  (where s₁² ≥ s₂²)",
        "test_stat_symbols": {
            "s₁²": "larger sample variance",
            "s₂²": "smaller sample variance",
            "n₁, n₂": "sample sizes",
        },
        "df_formula": "df₁ = n₁ − 1 (numerator),  df₂ = n₂ − 1 (denominator)",
        "ci_formula": "(s₁²/s₂²) / F_upper  to  (s₁²/s₂²) / F_lower  for σ₁²/σ₂²",
        "effect_size_name": "Variance ratio",
        "effect_size_formula": "s₁² / s₂²",
        "effect_size_scale": {"note": "No standard Cohen's scale; compare to F critical value"},
        "distribution": "F",
        "scipy_function": "scipy.stats.f (manual calculation)",
        "see_also": [
            ("chi_square_variance", "Use for a single variance"),
            ("two_sample_t_test_equal_var", "Run this F-test first to check the equal variance assumption"),
        ],
    },
}

# Ordered list matching the CLAUDE.md numbering
TOPIC_ORDER = [
    "one_sample_z_test", "one_sample_t_test", "one_sample_proportion_z_test",
    "two_sample_z_test", "two_sample_t_test_equal_var", "welchs_t_test",
    "paired_t_test", "two_proportion_z_test",
    "chi_square_goodness_of_fit", "chi_square_independence", "fishers_exact_test",
    "shapiro_wilk_test",
    "one_way_anova", "two_way_anova",
    "sign_test", "wilcoxon_signed_rank", "mann_whitney_u", "kruskal_wallis",
    "correlation_t_test", "regression_slope_t_test", "regression_f_test",
    "chi_square_variance", "f_test_two_variances",
]


def get_topic(topic_key):
    """Get a topic dict by key. Raises KeyError if not found."""
    return TOPICS[topic_key]


def get_all_topics():
    """Return all topics in the order they should be generated."""
    return [(key, TOPICS[key]) for key in TOPIC_ORDER]


def get_see_also(topic_key):
    """Return the see_also list for a topic."""
    return TOPICS[topic_key]["see_also"]
